name: backoff
desc: Runbook hub for backoff related issues
runbooks:
- name: pod-backoff
  desc: Runbook for pod backoff
  selectors:
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  doc: backoff/pod-backoff.md
