name: backoff
desc: Runbook hub for backoff related issues
runbooks:
- name: pod-backoff
  desc: Runbook for pod backoff
  selectors:
  - type: labelSelector
    selector: app=demo
  - type: labelSelector
    selector: demo=test1
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.kind}=secrets'
  doc: backoff/pod-backoff.md
- name: demo
  desc: demo
  selectors:
  - type: labelSelector
    selector: app=paymentmanager
  - type: labelSelector
    selector: app-id=appsab909ba8cbe61c46e1cb3f9c4dffd24b038a
  - type: labelSelector
    selector: app.kubernetes.io/managed-by=Helm
  - type: labelSelector
    selector: family=servicegroup
  - type: labelSelector
    selector: name=paymentmanager
  - type: labelSelector
    selector: released-by=gopaddle
  - type: labelSelector
    selector: servicegroup=paymentmanager-3yqw8yo3
  - type: labelSelector
    selector: servicegroup-name=paymentmanager
  - type: jsonPathSelector
    selector: '{.apiVersion}=apps/v1'
  - type: jsonPathSelector
    selector: '{.kind}=Deployment'
  - type: jsonPathSelector
    selector: '{.metadata.name}=paymentmanager'
  - type: jsonPathSelector
    selector: '{.metadata.namespace}=gopaddle'
  doc: backoff/demo.md
