name: backoff
desc: Runbook hub for backoff related issues
runbooks:
- name: pod-backoff
  desc: Runbook for pod backoff
  selectors:
  - type: labelSelector
    selector: app=demo
  - type: labelSelector
    selector: demo=test1
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.kind}=secrets'
  doc: backoff/pod-backoff.md
